language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install -r requirements.txt
script:
- coverage run tests/run_tests.py
after_success:
- codecov
deploy:
  provider: pypi
  user: gatkin
  password:
    secure: M3QTfMCjGCXV6YLMFlZ6M0+7UeHKBWFbubs0u4CYeCwmnWWKn1C/kx5oM4gqribhdA65vwz7cn4zKJYaNo0d0WBMhzU7YeZOD8rSQ47Tqfc4fceEWr4dLXsvzZsupqWHlrBHQWBtek8h5KP2GzF/nfn3+6iMZXiCTRC12zyhxbkdGrL1tJgTc8didu7Wm0h5kzfSDtfSQ5UnM5v8TZZM/lofbbfxcIBGzZ4RaCLBAeRd+XI8hIxleYZ54d7+slBpIwmCkRD5OdgVJO4to5nUutDV0xHYRi2pyMjcP7JtErt0cDdvnrZGgMl5XsIsqT/oWg6MIiBQwopU096CMySjdFC9HFZ+Jld5l9v06/PiuF4knoueNBIwIlhKVzb4K7rtLd37+uBjlzsbWXQ2aWlPhkKvGRL8fu8Yu7j6YdaXRoU4p7tIRKhmNG1QkwXvkCzrQfabF9zVD6PTRx+KC/WAD69CEu9Q5+cnxZjA0AvWb/l9JZqX+aYp0V7lTF37CxyKbQQ0sDyRmcNPb95sQtqgyhTa5O5odrlsRnAYCbMVMMcWsy/6cYchP6hPSq5G2ZrNsqu83k4f508SiaW2JI4FjCaBNX2SiSbGWQYRGmupFe5U9cfs4L7dN6hbhKV+iq8x3sAzJJRLlXUeysglFCbsbx1brvw2V5CiCrTOG2/q+6E=
  on:
    python: '3.6'
    branch: travis-deploy
    server: https://test.pypi.org/simple/
