language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install -r requirements.txt
script:
- coverage run tests/run_tests.py
after_success:
- codecov
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: gatkin
  password:
    secure: MF/F9E30wl7d98EH/S5SgVYjXhIAWVt/JQVr2TIvodWsNUocKVwYs1MWRPxTOF5IS2BZsd7DkMYfF80iqs36XnRaLccrEeY/HegO+Pv6v+VCXAWVSPBHT1xnO9qQCsr6Cvjbx/JmPGCb0bVQioRvFvgP8qF9K1fPFKghYQvwvX3w5a73PpaaUOb0IfcUMaH0rBtETUlP1kFqHd0i5xLl5qfzzYIdT3NcnkgCe+cpJ0rIAHze2LKe9qXu9XnVE5BLkKNYzC99HdUmt6KDIGJ9sCuJd7U+9O1PJS2h1RearaO02UWMgVTTAT5O/mK86v/M56tjxj5/JIHCTl+Cfh9rfw5agJ8hsYW26wUQGdZTlRwqRKPALTQ1QQjZBDuH5z9227zunc7Utgl2B/YjZkE3L4gWIlGpYFkqe6cIpcdNG0FxcOWyg3A8SmbvxzUBmBNdylR5eHtf5SxiZF8zdXgU2KHOLqaDbbaysUTmd7gQSuBvs4OthBF6xxYhYSEmEF2e70t3lL8Ecr8j0Z0Fbcfx/9wrQyNGg/pQRUJUSPfepAJd2x7p+ad8YnqmNEjoUxAEsHx+xVtrbgkt5ySWcCvqnRXtmwdLfHJeXc31DA1aRAZLURILQspN3FKwnH3IEv5K/qY4eIGlwR7aEzomNdEXbE27bL9Rt/kbiesjaf0V8Vs=
  on:
    python: '3.6'
    branch: travis-deploy
