language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install -r requirements.txt
script:
- coverage run tests/run_tests.py
after_success:
- codecov
deploy:
  provider: pypi
  user: gatkin
  password:
    secure: wlujjFmAmdhzmhg+1ruzWgrsYEqpiZXKCW7ASf6vC+VlBaXge8w5pLQT2g4rT1wWmoJQucmAdmBOX85e0X3REpwSHnnMNflazueS6IYg0a1Pyt6tan3eXUpBE87HgqNkHze1WWGuGBjVfTESlZ7vRxV3aon24mxInv7rAQYgkRo+XHYmYBdUrpklB65HBJfjHGunsUHg8EfRC+SgVKvVEyIrHzUumDwKk8imhztEvcBDkDmGV9beDaC+8XzkRYGqsjcGYqZpTQA/JxReTUtE9+vCojg+etQtqQURdknMxnPwzR7xFJpYjU/wORBVQiX5HVqq5hLn06rVkZdEsitWWzOwLAux5vCRE8Smio7X++GkWegMKDgmgl8nAsV8eP2UeqQZbrWK38yk1lezmrkaaRtt/i3N8Ho+vufyj8GT3Qb5Sc1AD4Z68ttYiMTvDJ9+Oe6ebGdRlhi/8ltrleCTmzz98NeV0J9VvbOjaHWQc8c2K+yE0KJNncDgVJSA1kf98tVGrbipk/OtwjM0o0tczRbZaFm6FZqgyHTe3I7qQNxahDOJYze+JO4UhdROahizLjtTWdVzUib4y6s8P9CD+qHELtcr0klCK3E70W6qcuNu7EN5DVDJQjKJDOpj/DU0DRqlFkged/FinNLzY/Y2bOLv5OYTPKsVGi5Rrigj94k=
  on:
    python: '3.6'
    branch: travis-deploy
    server: https://test.pypi.org/simple/
