jobs:
  - job: Lint
    pool:
      vmInage: 'Ubuntu 16.04'

    steps:
    - task: UsePythonVersion@0
      displayName: Setup Python
      inputs:
        versionSpec: '3.7'

    - script: 'make install'
      displayName: Install Dependencies

    - script: |
        pipenv run make check
        pipenv run make lint
      dispalyName: Lint
