jobs:
  - job: Lint
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
    - task: UsePythonVersion@0
      displayName: Setup Python
      inputs:
        versionSpec: '3.7.0'

    - template: azure-steps/install_deps.yml

    - bash: pipenv run make lint
      displayName: Lint
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - job: Docs
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
    - task: UsePythonVersion@0
      displayName: Setup Python
      inputs:
        versionSpec: '3.7.0'

    - template: azure-steps/install_deps.yml

    - script: |
        pipenv run make doccheck
      displayName: Build Docs

  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      maxParallel: 4
      matrix:
        python27:
          python.version: '2.7'
        python37:
          python.version: '3.7.0'

    steps:
    - template: azure-steps/test.yml
      parameters:
        python_version: '$(python.version)'

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      maxParallel: 4
      matrix:
        python27:
          python.version: '2.7'
        python37:
          python.version: '3.7.0'

    steps:
    - template: azure-steps/test.yml
      parameters:
        python_version: '$(python.version)'

  - job: MacOS
    pool:
      vmImage: 'macOS 10.13'
    strategy:
      maxParallel: 4
      matrix:
        python27:
          python.version: '2.7'
        python37:
          python.version: '3.7.0'

    steps:
    - template: azure-steps/test.yml
      parameters:
        python_version: '$(python.version)'

  - job: publish
    dependsOn:
    - Lint
    - Docs
    - Linux
    - Windows
    - MacOs
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
    - task: UsePythonVersion@0
      displayName: Setup Python
      inputs:
        versionSpec: '3.7.0'

    - task: PyPIPublisher@0
      displayName: Package and Publish to PyPI
      inputs:
        pypiConnection: pypi-conn
        packageDirectory: '$(System.DefaultWorkingDirectory)'
